title:             Farming Data
email:             info@farmingdata.io
description:       An agritech startup
author:            Farming Data
url:               "https://farmingdata.io"

enforce_ssl: farmingdata.io

# Social Profiles
twitter_username:  farming_data
facebook_username: farmingdata.io

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-paginate
